linters:
  enable-all: true
  disable:
    - cyclop
    - deadcode
    - dupword
    - exhaustruct
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goerr113
    - golint
    - gomnd
    - ifshort
    - inamedparam
    - interfacer
    - ireturn
    - lll
    - maligned
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - paralleltest
    - prealloc
    - predeclared
    - scopelint
    - structcheck
    - tagliatelle
    - testpackage
    - thelper
    - varcheck
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  depguard:
    rules:
      main:
        allow:
          - github.com/mmcloughlin/addchain
          - github.com/mmcloughlin/profile
          - github.com/google/subcommands
          - $gostd
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/mmcloughlin/addchain)
  revive:
    enable-all-rules: true
    confidence: 1.0
    rules:
      - name: add-constant
        disabled: true
      - name: bare-return
        disabled: true
      - name: confusing-naming
        disabled: true
      - name: cognitive-complexity
        disabled: true
      - name: cyclomatic
        disabled: true
      - name: deep-exit
        disabled: true
      - name: empty-block
        disabled: true
      - name: function-length
        disabled: true
      - name: import-shadowing
        disabled: true
      - name: line-length-limit
        disabled: true
      - name: max-public-structs
        disabled: true
      - name: unchecked-type-assertion
        disabled: true
      - name: unhandled-error
        arguments:
          - 'fmt\.(P|Fp)rint(ln|f)?'
      - name: unused-parameter
        disabled: true
      - name: unused-receiver
        disabled: true
      - name: use-any
        disabled: true

issues:
  exclude-use-default: false
  exclude:
    # gosec: G304: Potential file inclusion via variable.
    - G304
    # gosec: G306: Expect WriteFile permissions to be 0600 or less
    - G306
    # gosec: G404: Use of weak random number generator
    - G404
