linters:
  enable-all: true
  disable:
    - lll
    - gochecknoglobals
    - funlen
    - testpackage
    - gomnd
    - goerr113
    - wsl
    - gocognit

    # deprecated:
    - maligned
    - interfacer

    # new errors:
    - forbidigo
    - gci
    - gocritic
    - gosec
    - revive
    - cyclop
    - exhaustivestruct
    - ifshort
    - wrapcheck
    - wastedassign
    - paralleltest
    - nlreturn
    - predeclared
    - thelper

issues:
  exclude-use-default: false
  exclude:
    # gosec: G304: Potential file inclusion via variable.
    - G304
    # gosec: G306: Expect WriteFile permissions to be 0600 or less
    - G306
