linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - forbidigo
    - funlen
    - gci
    - gochecknoglobals
    - gocognit
    - gocritic
    - goerr113
    - gomnd
    - ifshort
    - interfacer
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - predeclared
    - revive
    - testpackage
    - thelper
    - wastedassign
    - wrapcheck
    - wsl

issues:
  exclude-use-default: false
  exclude:
    # gosec: G304: Potential file inclusion via variable.
    - G304
    # gosec: G306: Expect WriteFile permissions to be 0600 or less
    - G306
    # gosec: G404: Use of weak random number generator
    - G404
