linters:
  enable-all: true
  disable:
    - cyclop
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - goerr113
    - golint
    - gomnd
    - ifshort
    - interfacer
    - ireturn
    - lll
    - maligned
    - nlreturn
    - paralleltest
    - prealloc
    - predeclared
    - scopelint
    - tagliatelle
    - testpackage
    - thelper
    - varnamelen
    - wastedassign
    - wrapcheck
    - wsl

linters-settings:
  gci:
    sections:
     - standard
     - default
     - prefix(github.com/mmcloughlin/addchain)

issues:
  exclude-use-default: false
  exclude:
    # gosec: G304: Potential file inclusion via variable.
    - G304
    # gosec: G306: Expect WriteFile permissions to be 0600 or less
    - G306
    # gosec: G404: Use of weak random number generator
    - G404
