before:
  hooks:
  - go mod tidy
builds:
  - main: ./cmd/addchain
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X github.com/mmcloughlin/addchain/internal/meta.buildversion={{ .Version }}
archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*
changelog:
  skip: true
release:
  draft: true
  prerelease: auto
