#!/bin/bash

set -exuo pipefail

# Parse options.
all="false"
while getopts "a" opt; do
    case "${opt}" in
        a) all="true" ;;
    esac
done

# Run example program.
if [ "${all}" = "true" ]; then
    go install ./cmd/addchain
    bash ./internal/examples/cli/cmd.sh 2>&1 | tee ./internal/examples/cli/output
fi

# go generate
go generate -x ./...

# Bibliography.
bib generate -bib doc/references.bib -type markdown -output doc/bibliography.md

# Documentation.
go run ./internal/tools/docgen -type readme -tocmax 3 -output README.md
go run ./internal/tools/docgen -type results -output doc/results.md
go run ./internal/tools/docgen -type zenodo -output .zenodo.json
