#!/bin/bash

set -exuo pipefail

# Parse options.
all="false"
while getopts "a" opt; do
    case "${opt}" in
        a) all="true" ;;
    esac
done

# Run example programs.
if [ "${all}" = "true" ]; then
    bash ./internal/examples/cli/cmd.sh |& tee ./doc/examples/cli/output
fi

# go generate
go generate -x ./...

# Documentation.
go run ./internal/tools/docgen -type readme -output README.md
go run ./internal/tools/docgen -type results -output doc/results.md
