#!/bin/bash

set -exuo pipefail

# go generate
go generate -x ./...

# Documentation.
go run ./internal/tools/docgen -type readme -output README.md
go run ./internal/tools/docgen -type results -output doc/results.md
