permissions:
  contents: read

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "33 11 * * 6"

name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.15.x, 1.16.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8 # v2.1.3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=count ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@967e2b38a85a62bd61be5529ada27ebc109948c2 #v1.4.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
          flags: unittests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Go Environment
        run: |
          echo GOPATH=${{ runner.workspace }} >> $GITHUB_ENV
          echo ${{ runner.workspace }}/bin >> $GITHUB_PATH
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
        with:
          persist-credentials: false
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Lint
        run: ./script/lint
      - name: Generate
        run: ./script/generate -a
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
      - name: Format
        run: ./script/fmt
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
