on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: "33 11 * * 6"

name: ci
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -coverprofile=coverage.out -covermode=count ./...
      - name: Upload Coverage
        uses: codecov/codecov-action@v1.0.5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: coverage.out
          flags: unittests

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Go Environment
        run: |
          echo ::set-env name=GOPATH::${{ runner.workspace }}
          echo ::add-path::${{ runner.workspace }}/bin
      - name: Checkout code
        uses: actions/checkout@v1
      - name: Bootstrap
        run: ./script/bootstrap
      - name: Lint
        run: ./script/lint
      - name: Generate
        run: ./script/generate -a
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
      - name: Format
        run: ./script/fmt
      - name: Git Status
        run: |
          git diff
          test -z "$(git status --porcelain)"
